# Generated by Django 5.2.4 on 2025-07-17 11:07

import apps.businesses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(null=True, to='businesses.category', verbose_name='related categories'),
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='business',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='business',
            name='geo_latLng',
            field=models.CharField(max_length=100, null=True, verbose_name='geo coords'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram link'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin link'),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='geo location'),
        ),
        migrations.AddField(
            model_name='business',
            name='main_banner',
            field=models.ImageField(null=True, upload_to=apps.businesses.models.BusinessImagePath, verbose_name='main banner'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='business',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=apps.businesses.models.BusinessImagePath, verbose_name='profile image'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.TextField(null=True, verbose_name='services'),
        ),
        migrations.AddField(
            model_name='business',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='tiktok link'),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter_x',
            field=models.URLField(blank=True, null=True, verbose_name='twitter_x link'),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website link'),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='youtube link'),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=4)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='businesses.business')),
            ],
            options={
                'unique_together': {('business', 'day')},
            },
        ),
    ]
