# Generated by Django 5.2.4 on 2025-07-17 11:56

import apps.businesses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_category_business_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='section',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('top', 'Top'), ('popular', 'Popular'), ('new', 'New')], help_text='Used to categorize businesses in homepage sections', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.businesses.models.BusinessImagePath)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='businesses.business')),
            ],
        ),
    ]
