# Generated by Django 5.2.4 on 2025-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_section_businessgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='whatsapp link'),
        ),
    ]
