# Generated by Django 5.2.4 on 2025-07-18 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_whatsapp'),
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='malls.mall'),
        ),
        migrations.AddField(
            model_name='category',
            name='active_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BusinessKYCData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('registration_form', models.FileField(upload_to='')),
                ('mpesa_settlement_number', models.CharField(max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='businesses.business', verbose_name='business')),
            ],
        ),
    ]
