# Generated by Django 5.2.4 on 2025-07-18 11:22

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_business_mall_category_active_days_businesskycdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesskycdata',
            name='registration_form',
            field=models.FileField(blank=True, null=True, upload_to=apps.businesses.models.BusinessDocsPath),
        ),
    ]
