# Generated by Django 5.2.4 on 2025-07-18 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_businesskycdata_registration_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesskycdata',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kycdata', to='businesses.business', verbose_name='business'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('rating', models.PositiveIntegerField(verbose_name='rating')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='businesses.business', verbose_name='business')),
            ],
        ),
    ]
