# Generated by Django 5.2.4 on 2025-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_category_is_free_alter_businesskycdata_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(to='businesses.category', verbose_name='related categories'),
        ),
    ]
