# Generated by Django 5.2.4 on 2025-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_alter_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
    ]
