# Generated by Django 5.2.4 on 2025-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
