# Generated by Django 5.2.4 on 2025-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='twitter_x',
            new_name='twitterx',
        ),
    ]
