# Generated by Django 5.2.4 on 2025-07-19 13:33

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_rename_twitter_x_business_twitterx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='main_banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.businesses.models.BusinessImagePath, verbose_name='main banner'),
        ),
        migrations.AlterField(
            model_name='business',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.businesses.models.BusinessImagePath, verbose_name='profile image'),
        ),
    ]
