# Generated by Django 5.2.4 on 2025-07-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_business_main_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AlterField(
            model_name='business',
            name='geo_latLng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='geo coords'),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.category', verbose_name='related categories'),
        ),
    ]
