# Generated by Django 5.2.4 on 2025-07-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0013_remove_business_category_alter_business_geo_latlng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshour',
            name='is_closed',
        ),
    ]
