# Generated by Django 5.2.4 on 2025-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_alter_businesshour_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
