# Generated by Django 5.2.4 on 2025-07-21 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0016_business_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='geo_latLng',
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True, verbose_name='longitude'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.subcategory')),
            ],
        ),
    ]
