# Generated by Django 5.2.4 on 2025-07-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0018_business_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='businesses.category', verbose_name='related categories'),
        ),
    ]
