# Generated by Django 5.2.4 on 2025-07-21 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0019_alter_business_category'),
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_malls', to='malls.mall'),
        ),
    ]
