# Generated by Django 5.2.4 on 2025-07-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0020_alter_business_mall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='section',
            field=models.CharField(blank=True, choices=[('featured', 'Featured'), ('popular', 'Popular'), ('environs', 'Nairobi Environs'), ('new', 'New'), ('top', 'Top')], help_text='Used to categorize businesses in homepage sections', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business', verbose_name='business'),
        ),
    ]
