# Generated by Django 5.2.4 on 2025-08-12 07:20

import apps.businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_category_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='main_banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.businesses.models.BusinessImagePath, verbose_name='main banner'),
        ),
    ]
