# Generated by Django 5.2.4 on 2025-08-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_alter_business_main_banner'),
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_malls', to='malls.mall'),
        ),
    ]
