# Generated by Django 5.2.4 on 2025-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager'), ('owner', 'Owner')], max_length=20, null=True),
        ),
    ]
