# Generated by Django 5.2.4 on 2025-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager'), ('merchant', 'Merchant')], max_length=20, null=True),
        ),
    ]
