# Generated by Django 5.2.4 on 2025-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('manager', 'Manager'), ('merchant', 'Merchant'), ('professional', 'Professional')], max_length=20, null=True),
        ),
    ]
