# Generated by Django 5.2.4 on 2025-07-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boking_date',
            new_name='booking_date',
        ),
    ]
