# Generated by Django 5.2.4 on 2025-08-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_professionalprofile_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
