# Generated by Django 5.2.4 on 2025-08-04 04:12

import apps.professionals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_rename_phone_number_professionalprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.professionals.models.professionalImagePath),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.professionals.models.professionalImagePath),
        ),
    ]
