# Generated by Django 5.2.4 on 2025-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='consultation_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
