# Generated by Django 5.2.4 on 2025-08-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_professionalprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
