# Generated by Django 5.2.4 on 2025-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
