# Generated by Django 5.2.4 on 2025-08-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_booking_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='location_latLng',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=12, max_digits=16, null=True, verbose_name='longitude'),
        ),
    ]
