# Generated by Django 5.2.4 on 2025-08-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0012_remove_professionalprofile_location_latlng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
