# Generated by Django 5.2.4 on 2025-07-18 11:18

import apps.malls.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('main_image', models.ImageField(upload_to=apps.malls.models.MallImagePath, verbose_name='image')),
                ('floors', models.PositiveIntegerField(verbose_name='floors number')),
                ('stalls', models.PositiveIntegerField(verbose_name='stalls')),
                ('descriprion', models.TextField(verbose_name='description')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website link')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp link')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram link')),
                ('twitter_x', models.URLField(blank=True, null=True, verbose_name='twitter_x link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin link')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='tiktok link')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='youtube link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
