# Generated by Django 5.2.4 on 2025-07-24 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('client_name', models.CharField(max_length=60)),
                ('client_designation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
