# Generated by Django 5.2.4 on 2025-07-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
