# Generated by Django 5.2.4 on 2025-07-17 11:56

import apps.shop.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_business_section_businessgallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('main_image', models.ImageField(upload_to=apps.shop.models.ProductImagePath, verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='discounted price ')),
                ('is_discounted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business', verbose_name='related business')),
                ('category', models.ManyToManyField(to='businesses.category', verbose_name='categories')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ['-created_by'],
            },
        ),
    ]
