# Generated by Django 5.2.4 on 2025-07-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_alter_business_section_alter_review_business'),
        ('shop', '0002_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.category', verbose_name='categories'),
        ),
    ]
