# Generated by Django 5.2.4 on 2025-07-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0021_alter_business_section_alter_review_business'),
        ('shop', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='businesses.business', verbose_name='related business'),
        ),
    ]
